networks:
  network:
    name: cluster.net
    driver: bridge

volumes:
  alpha-home:
  beta-home:
  gamma-home:

services:
  jupyterhub:
    image: jupyterhub
    container_name: jupyterhub
    hostname: jupyterhub
    networks:
      - network
    environment:
      - PBS_SERVER=pbsserver
      - BINDER_API_TOKEN=binder-oauth-client-secret
      - BINDER_CLIENT_ID=service-oauth-client-binder
    ports:
      - 8000:8000
      - 8081:8081
    volumes:
      - alpha-home:/home/alpha
      - beta-home:/home/beta
      - gamma-home:/home/gamma

  binderhub:
    image: binderhub
    container_name: binderhub
    hostname: binderhub
    privileged: true
    networks:
      - network
    ports:
      - 8585:8585
    environment:
      - JUPYTERHUB_API_TOKEN=binder-oauth-client-secret
      - JUPYTERHUB_API_URL=http://jupyterhub:8081/hub/api
      - JUPYTERHUB_CLIENT_ID=service-oauth-client-binder
      - JUPYTERHUB_SERVICE_PREFIX=/
      - JUPYTERHUB_SERVICE_URL=http://localhost:8585
      - JUPYTERHUB_OAUTH_CALLBACK_URL=http://localhost:8585/oauth_callback
      - JUPYTERHUB_HOST=http://localhost:8000

  head:
    image: head
    container_name: head
    hostname: head
    privileged: true
    networks:
      - network
    environment:
      - PBS_SERVER=pbsserver
    volumes:
      - alpha-home:/home/alpha
      - beta-home:/home/beta
      - gamma-home:/home/gamma

  pbsserver:
    image: pbsserver
    container_name: pbsserver
    hostname: pbsserver
    networks:
      - network
    command: ["node"]

  node:
    depends_on:
      - pbsserver
    image: pbsmom
    container_name: node
    hostname: node
    privileged: true
    networks:
      - network
    environment:
      - PBS_SERVER=pbsserver
    volumes:
      - alpha-home:/home/alpha
      - beta-home:/home/beta
      - gamma-home:/home/gamma

  registry:
    image: docker.io/library/registry:2
    container_name: registry
    hostname: registry
    networks:
      - network
